vim.g.mapleader = " "
vim.keymap.set("n", "<leader>b", vim.cmd.NvimTreeToggle)
vim.keymap.set('n', '<C-k>', ':wincmd k<CR>', { silent = true })
vim.keymap.set('n', '<C-j>', ':wincmd j<CR>', { silent = true })
vim.keymap.set('n', '<C-h>', ':wincmd h<CR>', { silent = true })
vim.keymap.set('n', '<C-l>', ':wincmd l<CR>', { silent = true })
vim.keymap.set('n', '<C-x>', ':q<CR>')
vim.keymap.set('n', '<C-s>', ':w<CR>')
vim.keymap.set('i', '<C-x>', '<ESC>:q<CR>')
vim.keymap.set('i', '<C-s>', '<ESC>:w<CR>i<Right>')
vim.keymap.set('n', '<C-\\>', ':vsp<CR>')
vim.keymap.set('t', '<ESC>', '<C-\\><C-n>', {noremap = true})
vim.keymap.set('t', '<C-q>', '<C-\\><C-n>:ToggleTerm<CR>', { silent = true })
vim.keymap.set('n', '<C-q>', ':ToggleTerm<CR>i', { silent = true })
vim.keymap.set('i', '<C-q>', '<C-\\><C-n>:ToggleTerm<CR>i', { silent = true })
vim.keymap.set('n', '<C-Space>h', ':ToggleTerm direction=horizontal<CR>i', { silent = true })
vim.keymap.set('n', '<C-Space>f', ':ToggleTerm direction=float<CR>i', { silent = true })
vim.keymap.set('n', '<C-Up>', '<C-Y>', { noremap = true })
vim.keymap.set('n', '<C-Down>', '<C-E>', { noremap = true })
vim.keymap.set('i', '<CR>', [[coc#pum#visible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"]], { expr = true, silent = true })
vim.keymap.set('n', '<Tab>', ':set wrap! wrap?<CR>', { noremap = true, silent = true })
