vim.g.mapleader = " "
vim.keymap.set("n", "<leader>b", vim.cmd.NvimTreeToggle, { desc = "Toggle file explorer" })
vim.keymap.set('n', '<C-k>', ':wincmd k<CR>', { silent = true, desc = "Move up window" })
vim.keymap.set('n', '<C-j>', ':wincmd j<CR>', { silent = true, desc = "Move down window" })
vim.keymap.set('n', '<C-h>', ':wincmd h<CR>', { silent = true, desc = "Move left window" })
vim.keymap.set('n', '<C-l>', ':wincmd l<CR>', { silent = true, desc = "Move right window" })
vim.keymap.set('n', '<C-x>', ':q<CR>', { desc = "Close window" })
vim.keymap.set('n', '<C-s>', ':w<CR>', { desc = "Save file" })
vim.keymap.set('i', '<C-x>', '<ESC>:q<CR>', { desc = "Close window" })
vim.keymap.set('i', '<C-s>', '<ESC>:w<CR>i<Right>', { desc = "Save file" })
vim.keymap.set('n', '<C-\\>', ':vsp<CR>', { desc = "Split screen" })
vim.keymap.set('t', '<ESC>', '<C-\\><C-n>', { noremap = true, desc = "Exit terminal mode" })
vim.keymap.set('t', '<C-q>', '<C-\\><C-n>:ToggleTerm<CR>', { silent = true, desc = "Toggle terminal" })
vim.keymap.set('n', '<C-q>', ':ToggleTerm<CR>i', { silent = true, desc = "Toggle terminal" })
vim.keymap.set('i', '<C-q>', '<C-\\><C-n>:ToggleTerm<CR>i', { silent = true, desc = "Toggle terminal" })
vim.keymap.set('n', '<C-Space>h', ':ToggleTerm direction=horizontal<CR>', { silent = true, desc = "Toggle horizontal terminal" })
vim.keymap.set('n', '<C-Space>f', ':ToggleTerm direction=float<CR>', { silent = true, desc = "Toggle floating terminal" })
vim.keymap.set('n', '<C-Up>', '<C-Y>', { noremap = true, desc = "Scroll up" })
vim.keymap.set('n', '<C-Down>', '<C-E>', { noremap = true, desc = "Scroll down" })
vim.keymap.set('i', '<CR>', [[coc#pum#visible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"]], { expr = true, silent = true, desc = "Select suggestion" })
vim.keymap.set('n', '<Tab>', ':set wrap! wrap?<CR>', { noremap = true, silent = true, desc = "Toggle text wrap" })
vim.keymap.set('i', '<C-H>', '<ESC>dbi', { desc = "Delete word backwards" })
vim.keymap.set('i', '<C-Del>', '<ESC>dwi', { desc = "Delete word forwards" })
